export const FETCH_RECENT_QUESTIONS = 'FETCH_RECENT_QUESTIONS';
export const FETCH_SINGLE_QUESTION = 'FETCH_RECENT_QUESTIONS';
export const USER_SIGNUP = 'USER_SIGNUP';
export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';
export const SIGNUP_ERRORS = 'SIGNUP_ERRORS';